pipeline {
    agent any

    stages {
        stage('Setup Environment') {
            steps {
                sh 'echo "Setting up environment..."'
            }
        }
        stage('Download data') {
            steps {
                sh 'python3 HW2/data_creation.py'
            }
        }
        stage('Preprocess Data') {
            steps {
                sh 'python3 HW2/model_preprocessing.py'
            }
        }
        stage('Train model') {
            steps {
                sh 'python3 HW2/model_preparation.py'
            }
        }
        stage('Test Model') {
            steps {
                sh 'python3 HW2/model_testing.py'
            }
        }
    }
    post {
        always {
            sh 'echo "Pipeline completed"'
        }
    }
}