pipeline {
    agent any

    stages {
        stage('Setup Environment') {
            steps {
                sh 'echo "Setting up environment..."'
                //sh 'apt update'
                //sh 'apt install -y python3 python3-pip python3-venv'
                //sh 'python3 -m venv venv'
                //sh 'source venv/bin/activate'
                //sh 'pip install -r requirements.txt'
            }
        }
        stage('Download data') {
            steps {
                sh 'python3 HW2/data_creation.py'
            }
        }
        stage('Preprocess Data') {
            steps {
                sh 'python3 HW2/model_preprocessing.py'
            }
        }
        stage('Train model') {
            steps {
                sh 'python3 HW2/model_preparation.py'
            }
        }
        stage('Test Model') {
            steps {
                sh 'python3 HW2/model_testing.py'
            }
        }
    }
    post {
        always {
            sh 'echo "Pipeline completed"'
        }
    }
}